apiVersion: v1
kind: Service
metadata:
  name: java
  namespace: atul
  labels:
    app: java
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
